config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
#   get 'errors/not_found'
#   get 'errors/internal_server_error'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"

  delete 'members/destroy' => "members#destroy"
  post 'members/edit' => "members#edit"

  resources :projects do
    resources :attachments, only: [:index, :create] do
        post :destroy
    end
    
    resources :topics do 
        delete :destroy
        resources :messages
    end
    resources :members
  end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :project
    has_many :messages
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def index
        @topics = Project.find(params[:project_id]).topics
    end

    def new
        @topic = Topic.new
    end

    def edit
        @project = Project.find(params[:project_id])
        @topic = Topic.find(params[:id])
    end

    def create
        project = Project.find(params[:project_id])
        @Topic = project.topics.build(post_params)

        if @Topic.save
            flash[:notice] = "Successfully task added"
            redirect_to request.referer
        else
            flash[:alert] = "Failed to save"
            redirect_to request.referer
        end
    end

    def update
        @project = Project.find(params[:project_id])
        @topic = Topic.find(params[:id])
        if @topic.update(post_params)
          flash[:success] = "Topic item successfully updated!"
          redirect_to project_topics_path
        else
          flash.now[:error] = "Topic item update failed"
        end
    end

    def destroy
        @Topic = Topic.find(params[:id])

        @Topic.messages.destroy_all if @Topic.messages
        
        @Topic.destroy
        flash[:success] = "The to-do item was successfully destroyed."
        redirect_to request.referer
    end

    private

    def post_params
        params.require(:topic).permit(:title)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_new.html.erb
<% if current_user.has_role? :member, Project.find(params[:project_id]) %>
    <h1 class="mb-4">Messages</h1>
<% else %>
    <%= form_for :topic, url: project_topics_path(params[:project_id]), class: "d-flex align-items-center" do |form| %>
        <div style="margin-bottom: 1.5rem;" >
            <%= form.label :title, style: "display: block" %>
            <%= form.text_field :title, :required => 'required', class: "form-control"%>
        </div>
        <%= form.submit "Add new Topic", class: "btn btn-dark", style: "margin-left: 20px;"%>
    <% end %>
<% end %>

app/views/topics/_topic.html.erb
<div class="col-12 mb-4">
    <div class="card border-dark">
        <div class="card-header bg-light border">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <%= item.title %>
                </div>
                <div class="d-flex">
                    <%= link_to "Edit", edit_project_topic_path(params[:project_id], item.id), class: "btn btn-dark", style: "margin-right: 5px;" %>
                    <%= button_to "Delete", project_topic_path(params[:project_id], item.id), method: :delete, class: "btn btn-danger" %>
                </div>
            </div>
        </div>
        <div class="card-body overflow-auto messages_list">

            <div class="row message">
                <div class="col">
                    <% item.messages.each do |message| %>
                        <div class="d-flex justify-content-between">
                            <div>
                                <p class="font-weight-bold text-secondary"><%= User.find(message.user_id).name %></p>
                                <p><%= message.message %></p>
                            </div>
                            <div class="mt-3">
                                <%= link_to "Edit", edit_project_topic_message_path(params[:project_id], item.id, message.id), class: "link-dark" %>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
            
        </div>
        <div class="card-body border bg-light">
            <div class="row message">
                <%= form_for :message, url: project_topic_messages_path(params[:project_id], item.id), class: "d-flex" do |form|%>
                    <div class="text-field w-100">
                        <%= form.text_field :message ,placeholder: "Message", class: "form-control w-100"%>
                    </div>
                    <div>
                        <%= form.submit "Send", class: "btn btn-dark" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/topics/edit.html.erb
<div class="d-flex justify-content-center mt-5">
    <div class="col-5">
        <div class="text-center">
            <h1>Edit Topic</h1>
        </div>
        <div>
           <%= form_with(model: [@project, @topic], class: "d-flex") do |form| %>
            <div class="field w-75">
                <%= form.label :title, style: "display: block" %>
                <%= form.text_field :title, class: "form-control", value: @topic.title, style: "margin-bottom: .5rem;"%>
            </div>
            <div class="submit d-flex align-items-center">
                <%= form.submit "Update", class: "btn btn-dark", style: "margin-left: 20px;"%>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/topics/index.html.erb
<div class="d-flex flex-column align-items-center vh-100 mt-4">
    <%= render "new" %>
    <div class="row col-6" style="width: 600px;">
        <% @topics.each do |item| %>
            <%= render "topic", item: item %>
        <% end %>
    </div>
</div>