config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
#   get 'errors/not_found'
#   get 'errors/internal_server_error'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"

  delete 'members/destroy' => "members#destroy"
  post 'members/edit' => "members#edit"

  resources :projects do
    resources :attachments, only: [:index, :create] do
        post :destroy
    end
    
    resources :topics do 
        delete :destroy
        resources :messages
    end
    resources :members
  end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  
end

app/models/project.rb
class Project < ApplicationRecord
#   has_many :tasks
  belongs_to :user
  has_many :members
  has_many_attached :files, dependent: :destroy
  has_many :topics
  
  resourcify

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = current_projects
  end

  # GET /projects/1 or /projects/1.json
  def show
    @members = show_members
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
    if not_admin?()
        redirect_to project_path, 
        alert: "
        You are without administrator rights"
    end
  end


  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)
    
    respond_to do |format|
      if @project.save
        current_user.add_role :creator, @project
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_projects.find_by(id: params[:id])
      
      redirect_to projects_path, notice: "Not Authorized To Edit This Project!" if @project.nil?
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :files)
    end

    # Find projects that belong to them
    def current_projects
      Project.with_roles([:creator, :member, :member_admin], current_user)
    end

    def show_members 
        @project = Project.find(params[:id])
        User.with_any_role(:member, { name: :member, resource: @project }, { name: :member_admin, resource: @project })
    end

    def not_admin?
        current_user.has_role? :member, Project.find(params[:id])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
    <% if project.errors.any? %>
        <div style="color: red">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
            <% project.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name, :required => true, class: "form-control" %>
    </div>

    <div class="field">
        <%= form.label :description, style: "display: block" %>
        <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="d-flex justify-content-between">
        <%= form.submit nil, :class => 'btn btn-dark'%>
        <div class="d-flex align-items-center">
            <%= link_to "Back to projects", projects_path, class: "link-dark" %>
        </div>
    </div>
<% end %>

app/views/projects/_project.html.erb
<div class="col" id="<%= dom_id project %>">
    <div class="border m-3 rounded card">
        <div class="p-3 bg-dark text-white rounded-top">
            <strong>Name:</strong>
            <%= project.name %><br/>
            <strong>Created by:</strong>
            <%= User.with_role(:creator, project)[0][:name] %>
        </div>

        <div class="descrition_item">
            <div class="text-center bg-secondary">
                <small class="form-text text-white">Description:</small><br/>
            </div>
            <div class="card-body scroll">
                <p class="overflow-auto">
                <%= project.description %>
                </p>
            </div>
        </div>
        <div class="p-3 bg-light text-dark  rounded-bottom">
            <%= link_to "Show", project, class: "link-dark"%>
            |&nbsp<%= link_to "Edit", edit_project_path(project.id), class: "link-dark"%>
        </div>
    </div>
</div>

app/views/projects/edit.html.erb
<% content_for :title do %>
    Project&nbsp№<%=params[:id]%>&nbspEdit
<% end %>
<div class="d-flex justify-content-center mt-5">
    <div style="width: 600px">
        <div class="text-center">
            <h1>Editing project</h1>
        </div>

        <%= render "form", project: @project %>
        <%= render "members/form"%>
    </div>
</div>

app/views/projects/index.html.erb
<% content_for :title do %>
    Projects
<% end %>
<div class="border rounded mt-5">  

    <div class="m-3"><h1>Projects</h1>
    <% if @projects.empty? %>
        <%= link_to  "Add Project", new_project_path, class: "btn btn-dark" %>
    <% end %>
    </div>

    <div id="projects" class="row row-cols-2">

    <% @projects.each do |project| %>
        <%= render project %>
    <% end %>
    
    </div>
</div>

app/views/projects/new.html.erb
<div class="d-flex justify-content-center mt-5">   
    <div style="width: 500px">
        <div class="text-center">
            <h1>New project</h1>
        </div>

        <%= render "form", project: @project %>

    </div>
</div>

app/views/projects/show.html.erb
<% content_for :title do %>
    Project&nbsp;№<%=params[:id]%> 
<% end %>
<div class="d-flex mt-5 justify-content-evenly">
    <div style="flex-basis: 15%;"></div>
    <div class="w-75">
        <%= render "projects/show/show_project", project: @project, members: @members %>

        
        <div class="m-3 d-flex justify-content-between">
            <% if current_user.has_role? :member, Project.find(params[:id])%>
                <%= form_for :destroy, url: members_destroy_path, method: :delete do |form| %>
                    <%= form.hidden_field  :id, value: current_user.id %>
                    <%= form.hidden_field  :project_id, value: params[:id]%>
                    <%= form.submit "Delete from yourself", class: "btn btn-danger", style: "margin-right: 10px;" %>
                <% end %>
            <% else %>
                <div>
                    <%= link_to "Edit this project", edit_project_path(@project), class: "link-dark" %> |
                    <%= link_to "Back to projects", projects_path, class: "link-dark" %>
                </div>
                <%= button_to "Destroy this project", @project, method: :delete, class: "btn btn-danger" %>
            <% end %>
        </div>
    </div>
    <%= render "projects/show/navigation", members: @members %>
</div>